import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronDown, ChevronRight, Clock3, FileText, Filter, MoreHorizontal, Plus, RefreshCcw, Search } from "lucide-react";
import { cn } from "@/lib/utils";

const records=[
 {id:"PRO-0042",title:"Gestão de fornecedores",type:"Procedimento",status:"Em ajustes",condition:"Requer sua ação",owner:"Patrícia Lima",review:"Hoje",action:"Responder ajustes"},
 {id:"PRO-0043",title:"Gestão de fornecedores críticos",type:"Procedimento",status:"Rascunho",condition:"Rascunho",owner:"Patrícia Lima",review:"Salvo há 12 min",action:"Continuar edição"},
 {id:"POL-0014",title:"Política de sustentabilidade",type:"Política",status:"Em aprovação",condition:"Aguardando alçada",owner:"Patrícia Lima",review:"31/08",action:"Acompanhar fluxo"},
 {id:"NOR-0018",title:"Gestão de terceiros",type:"Norma",status:"Vencido",condition:"Revisão necessária",owner:"Patrícia Lima",review:"Vencido há 12 dias",action:"Iniciar revisão"},
 {id:"POL-0009",title:"Política anticorrupção",type:"Política",status:"Vigente",condition:"Próxima revisão",owner:"Patrícia Lima",review:"Vence em 8 dias",action:"Iniciar revisão"},
 {id:"IT-0179",title:"Homologação de fornecedores",type:"Instrução",status:"Vigente",condition:"No prazo",owner:"Patrícia Lima",review:"04/09/2028",action:"Ver normativo"},
 {id:"PRO-0036",title:"Gestão de contratos",type:"Procedimento",status:"Vigente",condition:"No prazo",owner:"Patrícia Lima",review:"21/06/2029",action:"Ver normativo"},
 {id:"NOR-0011",title:"Segurança operacional",type:"Norma",status:"Revogado",condition:"Encerrado",owner:"Patrícia Lima",review:"Revogado em 10/05",action:"Ver histórico"},
];

export function MyNormativesView({onOpen,onNew}:{onOpen:(id:string)=>void;onNew:()=>void}){
 const [scope,setScope]=useState("Todos"); const [query,setQuery]=useState("");
 const filtered=useMemo(()=>records.filter(r=>{const q=`${r.id} ${r.title} ${r.type}`.toLowerCase().includes(query.toLowerCase());if(!q)return false;if(scope==="Todos")return true;if(scope==="Requer minha ação")return r.condition==="Requer sua ação"||r.status==="Rascunho";if(scope==="Em aprovação")return r.status==="Em aprovação"||r.status==="Em ajustes";if(scope==="Vigentes")return r.status==="Vigente";if(scope==="Revisão necessária")return r.condition==="Revisão necessária"||r.condition==="Próxima revisão";return true}),[scope,query]);
 return <div className="max-w-[1240px] mx-auto p-8 animate-fade-in normatives-content"><header className="flex items-start justify-between gap-5 mb-6"><div><div className="section-title mb-1.5">Seu acervo</div><h2 className="text-[25px] font-semibold">Meus Normativos</h2><p className="text-sm mt-1">Gerencie todos os normativos sob sua responsabilidade, do rascunho à revisão.</p></div><button onClick={onNew} className="h-10 px-4 rounded-lg bg-primary text-white text-sm font-medium flex items-center gap-2"><Plus className="h-4 w-4"/> Cadastrar normativo</button></header>
 <div className="grid grid-cols-5 gap-3 mb-5">{[["Total sob sua responsabilidade","28"],["Requerem sua ação","3"],["Em aprovação","5"],["Vigentes","17"],["Revisão necessária","3"]].map(([l,v],i)=><button key={l} onClick={()=>i===0?setScope("Todos"):i===1?setScope("Requer minha ação"):i===2?setScope("Em aprovação"):i===3?setScope("Vigentes"):setScope("Revisão necessária")} className={cn("bg-card border rounded-xl p-4 text-left hover:border-primary/30",(i===0&&scope==="Todos")||(i===1&&scope==="Requer minha ação")||(i===2&&scope==="Em aprovação")||(i===3&&scope==="Vigentes")||(i===4&&scope==="Revisão necessária")?"border-primary ring-1 ring-primary/10":"")}><div className="text-xl font-semibold">{v}</div><div className="text-[9px] text-muted-foreground mt-1 leading-4">{l}</div></button>)}</div>
 <div className="bg-card border rounded-xl overflow-hidden"><div className="px-5 pt-4 border-b flex gap-5 overflow-x-auto">{["Todos","Requer minha ação","Em aprovação","Vigentes","Revisão necessária"].map(x=><button key={x} onClick={()=>setScope(x)} className={cn("pb-3 text-[11px] whitespace-nowrap border-b-2 -mb-px",scope===x?"border-primary text-primary font-medium":"border-transparent text-muted-foreground")}>{x}</button>)}</div><div className="p-4 border-b flex gap-3"><div className="relative flex-1"><Search className="h-4 w-4 absolute left-3 top-2.5 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full h-9 border rounded-lg pl-9 pr-3 text-xs" placeholder="Buscar código, título ou tipo..."/></div>{["Status","Tipo","Prazo de revisão"].map(x=><button key={x} className="h-9 px-3 border rounded-lg text-[10px] flex items-center gap-2">{x}<ChevronDown className="h-3.5 w-3.5"/></button>)}<button className="h-9 px-3 text-[10px] text-muted-foreground flex items-center gap-2"><Filter className="h-3.5 w-3.5"/> Mais filtros</button></div>
 <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="bg-surface-subtle text-[9px] uppercase tracking-wide text-muted-foreground"><th className="px-5 py-3 font-medium">Normativo</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 font-medium">Situação</th><th className="px-4 py-3 font-medium">Revisão / prazo</th><th className="px-4 py-3 font-medium">Próxima ação</th><th/></tr></thead><tbody className="divide-y">{filtered.map(r=><tr key={r.id} className={cn("transition-colors",rowHighlight(r),"hover:brightness-[.985]")}><td onClick={()=>onOpen(r.id)} className="px-5 py-4 cursor-pointer"><div className="text-xs font-semibold">{r.title}</div><div className="text-[9px] text-muted-foreground mt-1">{r.id} · {r.type} · Responsável: {r.owner}</div></td><td className="px-4 py-4"><Pill value={r.status}/></td><td className="px-4 py-4"><div className="flex items-center gap-2 text-[10px]">{r.condition==="Requer sua ação"||r.condition==="Revisão necessária"?<AlertTriangle className="h-3.5 w-3.5 text-amber-600"/>:r.condition==="No prazo"?<CheckCircle2 className="h-3.5 w-3.5 text-emerald-500"/>:<Clock3 className="h-3.5 w-3.5 text-muted-foreground"/>}{r.condition}</div></td><td className="px-4 py-4 text-[10px] text-muted-foreground">{r.review}</td><td className="px-4 py-4"><button onClick={()=>onOpen(r.id)} className="text-[10px] text-primary font-medium">{r.action}</button></td><td className="px-3"><button aria-label={`Mais ações para ${r.id}`}><MoreHorizontal className="h-4 w-4 text-muted-foreground"/></button></td></tr>)}</tbody></table></div><div className="px-5 py-3 border-t text-[10px] text-muted-foreground">Exibindo {filtered.length} de 28 normativos sob sua responsabilidade</div></div></div>
}
function rowHighlight(r:(typeof records)[number]){if(r.condition==="Requer sua ação")return "bg-amber-50/55 shadow-[inset_3px_0_0_#f59e0b]";if(r.condition==="Revisão necessária")return "bg-red-50/45 shadow-[inset_3px_0_0_#ef4444]";if(r.status==="Rascunho")return "bg-blue-50/35 shadow-[inset_3px_0_0_#3b82f6]";if(r.condition==="Próxima revisão")return "bg-amber-50/25 shadow-[inset_3px_0_0_#fbbf24]";return "hover:bg-muted/35"}
function Pill({value}:{value:string}){const c=value==="Vencido"?"bg-red-50 text-red-700":value==="Vigente"?"bg-emerald-50 text-emerald-700":value==="Em aprovação"||value==="Em ajustes"?"bg-amber-50 text-amber-800":value==="Rascunho"?"bg-slate-100 text-slate-700":"bg-muted text-muted-foreground";return <span className={cn("text-[9px] rounded px-2 py-1",c)}>{value}</span>}
