import { useState } from "react";
import { AlertTriangle, Archive, Bot, CheckCircle2, ChevronRight, Clock3, FileText, History, Plug, Save, ShieldCheck, Workflow } from "lucide-react";
import { cn } from "@/lib/utils";

const sections = [
  ["templates", "Tipos e documentos", FileText, "4"], ["routing", "Fluxos e alçadas", Workflow, "4"],
  ["sla", "Prazos e SLAs", Clock3, "7"], ["ai", "IA e validações", Bot, "5"],
  ["integrations", "Integrações", Plug, "3"], ["lifecycle", "Ciclo de vida", Archive, "auto"],
] as const;

export function NormativeSettingsPanel() {
  const [active, setActive] = useState("templates");
  return <div className="max-w-[1240px] mx-auto p-8 animate-fade-in normatives-content">
    <header className="flex items-start justify-between mb-6"><div><div className="section-title mb-1.5">Administração</div><h2 className="text-[25px] font-semibold">Configurações</h2><p className="text-sm mt-1">Regras versionadas que governam o ciclo de vida dos normativos.</p></div><div className="flex gap-2"><button className="h-9 px-3 border rounded-lg text-xs flex items-center gap-2"><History className="h-4 w-4" /> Histórico</button><button className="h-9 px-4 bg-primary text-white rounded-lg text-xs font-medium flex items-center gap-2"><Save className="h-4 w-4" /> Salvar alterações</button></div></header>
    <div className="bg-amber-50 border border-amber-100 rounded-xl p-3.5 flex gap-3 mb-5"><AlertTriangle className="h-4 w-4 text-amber-700 mt-0.5" /><p className="text-[11px] text-amber-900">Antes de publicar uma alteração, o sistema mostrará quais demandas em andamento serão afetadas.</p></div>
    <div className="grid grid-cols-[230px_minmax(0,1fr)] gap-5 normatives-dashboard-grid">
      <aside className="bg-card border rounded-xl p-3 h-fit"><div className="px-3 py-2 text-[10px] uppercase tracking-wide text-muted-foreground">Configuração v2.3</div>{sections.map(([id,label,Icon,count])=><button key={id} onClick={()=>setActive(id)} className={cn("w-full rounded-lg px-3 py-2.5 flex items-center gap-3 text-xs mb-1",active===id?"bg-primary/5 text-primary font-medium":"text-muted-foreground hover:bg-muted/50 hover:text-foreground")}><Icon className="h-4 w-4"/><span className="flex-1 text-left">{label}</span><span className="text-[9px] bg-muted rounded px-1.5 py-0.5">{count}</span></button>)}</aside>
      <section>{active==="templates"&&<Templates/>}{active==="routing"&&<Routing/>}{active==="sla"&&<Sla/>}{active==="ai"&&<AiRules/>}{active==="integrations"&&<Integrations/>}{active==="lifecycle"&&<Lifecycle/>}</section>
    </div>
  </div>;
}

function PanelHeader({ title, description, badge }: { title:string; description:string; badge:string }) { return <div className="mb-5"><div className="flex items-center gap-2 mb-1"><h3 className="text-lg font-semibold">{title}</h3><span className="text-[9px] bg-primary/5 text-primary rounded px-2 py-1">{badge}</span></div><p className="text-xs">{description}</p></div>; }
function Templates(){const [type,setType]=useState("POL");return <div><PanelHeader title="Tipos e documentos" badge="Entrada de demandas" description="Código, template, vigência e campos obrigatórios por tipo documental."/><div className="flex gap-2 mb-4">{["POL","NOR","PRO","IT"].map(x=><button key={x} onClick={()=>setType(x)} className={cn("h-8 px-4 rounded-lg border text-xs",type===x?"bg-primary text-white border-primary":"bg-card")}>{x}</button>)}</div><div className="grid grid-cols-2 gap-4"><SettingCard title="Codificação automática" action="Editar"><div className="text-sm font-semibold text-primary">{type}-{'{seq:03}'}</div><p className="text-[10px] mt-1">Próximo código: {type}-{type==="POL"?"020":type==="NOR"?"248":type==="PRO"?"0043":"0188"}</p></SettingCard><SettingCard title="Minuta padrão" action="Versões"><div className="text-xs font-medium">{type}_Template_v3.docx</div><p className="text-[10px] mt-1">Aplicada automaticamente na criação.</p></SettingCard><SettingCard title="Vigência padrão" action="Editar"><div className="text-sm font-semibold">{type==="POL"||type==="NOR"?"5":"3"} anos</div><p className="text-[10px] mt-1">Alertas em 90, 60 e 30 dias.</p></SettingCard><SettingCard title="Campos obrigatórios" action="Editar">{["Título","Processo corporativo","Responsável técnico","Escopo de aplicação"].map(x=><div key={x} className="flex gap-2 text-[10px] py-1"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-500"/>{x}</div>)}</SettingCard></div></div>}
function Routing(){return <div><PanelHeader title="Fluxos e alçadas" badge="Workflow" description="Sequência, responsáveis e alçada final por tipo documental."/><div className="bg-card border rounded-xl overflow-hidden"><div className="p-4 bg-surface-subtle border-b flex justify-between"><div><div className="text-xs font-semibold">Fluxo de Política (POL)</div><p className="text-[10px] mt-1">SLA total estimado: 15 dias úteis</p></div><button className="text-xs text-primary font-medium">Editar fluxo</button></div>{[["Normativos","Equipe Normativos","3 dias","Obrigatória"],["Compliance","Equipe Compliance","3 dias","Obrigatória"],["Governança Corporativa","Governança","3 dias","Obrigatória"],["Jurídico","Departamento Jurídico","3 dias","Obrigatória"],["DE + CA","Deliberação externa","5 dias","Externa"]].map(([stage,owner,sla,status],i)=><div key={stage} className="p-4 border-b last:border-0 grid grid-cols-[32px_1.2fr_1fr_70px_80px] items-center gap-3"><div className="w-7 h-7 bg-primary/5 text-primary rounded-full flex items-center justify-center text-[10px] font-semibold">{i+1}</div><div className="text-xs font-medium">{stage}</div><div className="text-[10px] text-muted-foreground">{owner}</div><div className="text-[10px]">{sla}</div><span className={cn("text-[9px] rounded px-2 py-1 text-center",status==="Externa"?"bg-amber-50 text-amber-800":"bg-emerald-50 text-emerald-700")}>{status}</span></div>)}</div></div>}
function Sla(){return <div><PanelHeader title="Prazos e SLAs" badge="7 regras" description="Prazos, alertas automáticos e escalonamentos por etapa."/><div className="bg-card border rounded-xl overflow-hidden"><div className="grid grid-cols-[1.2fr_90px_1fr] bg-surface-subtle px-4 py-3 text-[10px] uppercase text-muted-foreground"><span>Etapa</span><span>SLA</span><span>Escalonamento</span></div>{[["Análise de Normativos","3 dias","VP + área"],["Validação de Compliance","3 dias","VP + Compliance"],["Validação de Riscos","3 dias","Comitê de Riscos"],["Governança Corporativa","3 dias","VP + Governança"],["Validação Jurídica","3 dias","Jurídico + VP"],["Aprovação gerencial","4 dias","VP da área"],["Aprovação da VP","4 dias","Diretoria"]].map(([stage,sla,escalation])=><div key={stage} className="grid grid-cols-[1.2fr_90px_1fr] px-4 py-3 border-t items-center"><span className="text-xs font-medium">{stage}</span><button className="w-16 h-7 border rounded text-[10px]">{sla}</button><span className="text-[10px] text-muted-foreground">Após violação: {escalation}</span></div>)}</div><div className="mt-4 bg-[#F7F8FF] border border-[#E3E7FF] rounded-xl p-4 flex items-center"><Clock3 className="h-4 w-4 text-primary mr-3"/><div className="flex-1"><div className="text-xs font-medium">Follow-up automático</div><p className="text-[10px] mt-1">E-mail e notificação interna 3 dias úteis antes do vencimento.</p></div><button className="text-[10px] text-primary font-medium">Editar regra</button></div></div>}
function AiRules(){return <div><PanelHeader title="IA e validações" badge="5 ativas" description="Recomendações assistivas configuráveis, sempre sujeitas à decisão humana."/><div className="space-y-3">{[["Classificação documental","Verifica se POL, NOR, PRO ou IT está adequado.","Sensibilidade 70%"],["Detecção de sobreposição","Compara com a biblioteca de normativos vigentes.","Alerta acima de 15%"],["Apoio à redação","Sugere clareza, consistência e completude.","Não altera automaticamente"],["Checklist de qualidade","Avalia nove dimensões de qualidade e conformidade.","9 critérios"],["Vínculo com processos","Sugere processos e subprocessos relacionados.","Ativo na criação"]].map(([title,description,param])=><div key={title} className="bg-card border rounded-xl p-4 flex items-center gap-4"><div className="w-9 h-9 bg-primary/5 text-primary rounded-lg flex items-center justify-center"><Bot className="h-4 w-4"/></div><div className="flex-1"><div className="text-xs font-semibold">{title}</div><p className="text-[10px] mt-1">{description}</p></div><div className="text-right"><div className="text-[9px] text-muted-foreground mb-2">{param}</div><button className="h-6 w-11 bg-emerald-500 rounded-full relative" aria-label={`Ativar ${title}`}><span className="absolute w-4 h-4 bg-white rounded-full right-1 top-1"/></button></div></div>)}</div></div>}
function Integrations(){return <div><PanelHeader title="Integrações" badge="2 de 3 conectadas" description="Publicação, assinaturas e deliberações externas."/><div className="space-y-3"><Integration name="SharePoint" state="Conectado" description="Publicação automática, metadados e controle de versões." detail="/sites/normativos/{tipo}/{ano}/"/><Integration name="DocuSign" state="Conectado" description="Assinatura eletrônica opcional para IT e PRO." detail="Conta AXIA Energia" optional/><Integration name="Aprova" state="Não conectado" description="Encaminhamento opcional de Políticas ao Conselho." detail="Aguardando configuração" optional/></div></div>}
function Lifecycle(){return <div><PanelHeader title="Ciclo de vida e publicação" badge="Motor automático" description="Transições, publicação e monitoramento executados diariamente."/><div className="bg-[#0B1D48] text-white rounded-xl p-5 mb-4 flex items-center"><div><div className="text-xs text-white/60 mb-1">Saúde do motor</div><div className="text-sm font-semibold">0 falhas nas últimas 30 execuções</div><div className="text-[10px] text-white/55 mt-1">Próxima varredura amanhã às 06:00</div></div><div className="ml-auto text-right"><div className="text-2xl font-semibold">27</div><div className="text-[9px] text-white/55">ações automáticas / 24h</div></div></div><div className="grid grid-cols-5 gap-2 mb-4">{[["Em revisão","35"],["Vigente","143"],["Vencido","4"],["Revogado","18"],["Cancelado","7"]].map(([state,count])=><div key={state} className="bg-card border rounded-lg p-3"><div className="text-lg font-semibold">{count}</div><div className="text-[9px] text-muted-foreground mt-1">{state}</div></div>)}</div>{[["Publicação automática","Ao atingir Vigente, publica e sincroniza metadados no SharePoint."],["Vencimento automático","Vigência expirada sem revisão aberta altera o status e notifica responsáveis."],["Cancelamento por inatividade","Rascunho ou análise sem movimento por mais de 30 dias."],["Revogação por substituição","Ao publicar v(n), a versão v(n-1) é arquivada e revogada."]].map(([title,text])=><div key={title} className="bg-card border rounded-xl p-4 mb-2 flex items-center"><ShieldCheck className="h-4 w-4 text-primary mr-3"/><div className="flex-1"><div className="text-xs font-medium">{title}</div><p className="text-[10px] mt-1">{text}</p></div><ChevronRight className="h-4 w-4 text-muted-foreground"/></div>)}</div>}
function SettingCard({title,action,children}:{title:string;action:string;children:React.ReactNode}){return <div className="bg-card border rounded-xl p-4"><div className="flex justify-between mb-3"><div className="text-xs font-semibold">{title}</div><button className="text-[10px] text-primary font-medium">{action}</button></div>{children}</div>}
function Integration({name,state,description,detail,optional}:{name:string;state:string;description:string;detail:string;optional?:boolean}){return <div className="bg-card border rounded-xl p-5 flex items-center gap-4"><div className="w-10 h-10 bg-muted rounded-xl flex items-center justify-center"><Plug className="h-5 w-5 text-primary"/></div><div className="flex-1"><div className="flex gap-2 items-center"><div className="text-sm font-semibold">{name}</div>{optional&&<span className="text-[8px] bg-muted rounded px-1.5 py-0.5">OPCIONAL</span>}</div><p className="text-[10px] mt-1">{description}</p><div className="text-[9px] text-muted-foreground mt-1">{detail}</div></div><div className="text-right"><span className={cn("text-[9px] rounded px-2 py-1",state==="Conectado"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800")}>{state}</span><button className="block text-[10px] text-primary font-medium mt-3 ml-auto">{state==="Conectado"?"Configurar":"Conectar"}</button></div></div>}
