/* eslint-disable @typescript-eslint/no-explicit-any */
import { useMemo, useState, type ReactNode } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Check, ChevronRight, CircleHelp, Database, Eye, Focus, GitBranch, Layers3, Maximize2, Minus, Network, Plus, Search, ShieldCheck, UserRound, X } from 'lucide-react';
import { TopBar } from '@/components/layout/TopBar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import { cn } from '@/lib/utils';
import { useProcessStore } from '@/stores/processStore';
import { getProcessCanvas } from '@/data/processCanvasMockData';
import type { ProcessActivity, ProcessCanvas, ProcessDataObject, ProcessHandoff, ProcessSystem } from '@/types/processCanvas';

type Lens = 'journey' | 'systems' | 'data' | 'actors' | 'handoffs';
type Selection = { type: 'activity' | 'system' | 'data' | 'handoff'; id: string } | null;

const evidenceLabel: Record<string, string> = { observed: 'Observado', declared: 'Declarado', inferred: 'Inferido', validated: 'Validado' };
const interactionLabel: Record<string, string> = { receives: 'Recebe', reads: 'Consulta', creates: 'Cria', updates: 'Altera', sends: 'Envia', archives: 'Arquiva' };
const lensItems: Array<{ id: Lens; label: string; icon: typeof Layers3 }> = [
  { id: 'journey', label: 'Jornada', icon: Layers3 }, { id: 'systems', label: 'Sistemas', icon: Network }, { id: 'data', label: 'Dados', icon: Database }, { id: 'actors', label: 'Atores e áreas', icon: UserRound }, { id: 'handoffs', label: 'Handoffs', icon: GitBranch },
];

export function ProcessCanvasPage({ onLogout }: { onLogout: () => void }) {
  const navigate = useNavigate();
  const { id = 'demo' } = useParams();
  const process = useProcessStore(s => s.processes.find(p => p.id === id));
  const canvas = useMemo(() => getProcessCanvas(id), [id]);
  const [lens, setLens] = useState<Lens>('journey');
  const [selection, setSelection] = useState<Selection>(null);
  const [search, setSearch] = useState('');
  const [stageFilter, setStageFilter] = useState('all');
  const [systemFilter, setSystemFilter] = useState('all');
  const [areaFilter, setAreaFilter] = useState('all');
  const [zoom, setZoom] = useState(100);

  const processName = process?.name || 'Solicitação de compra';
  const filteredActivities = useMemo(() => canvas.activities.filter(activity => {
    const text = [activity.name, activity.description, ...activity.actorIds.map(a => canvas.actors.find(x => x.id === a)?.name || ''), ...activity.systemIds.map(s => canvas.systems.find(x => x.id === s)?.name || '')].join(' ').toLowerCase();
    return (!search || text.includes(search.toLowerCase())) && (stageFilter === 'all' || activity.stageId === stageFilter) && (systemFilter === 'all' || activity.systemIds.includes(systemFilter)) && (areaFilter === 'all' || activity.areaIds.includes(areaFilter));
  }), [canvas, search, stageFilter, systemFilter, areaFilter]);

  const selected = selection ? canvas[selection.type === 'activity' ? 'activities' : selection.type === 'system' ? 'systems' : selection.type === 'data' ? 'dataObjects' : 'handoffs'].find((item: any) => item.id === selection.id) : null;
  const clearFilters = () => { setSearch(''); setStageFilter('all'); setSystemFilter('all'); setAreaFilter('all'); };

  return <div className="min-h-screen bg-background flex flex-col"><TopBar onLogout={onLogout} /><main className="flex-1 min-w-0">
    <div className="px-7 pt-6 pb-4 border-b border-border bg-card">
      <div className="flex items-center gap-2 text-xs text-muted-foreground mb-4"><button className="hover:text-primary" onClick={() => navigate('/processes')}>Processos</button><ChevronRight className="h-3.5 w-3.5" /><button className="hover:text-primary" onClick={() => navigate(`/processes/${id}`)}>Detalhe do processo</button><ChevronRight className="h-3.5 w-3.5" /><span>Process Intelligent Canvas</span></div>
      <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><h1 className="text-[25px] leading-tight">{processName}</h1><Badge variant="outline" className="gap-1 font-normal"><Eye className="h-3 w-3" />AS-IS · Em revisão</Badge></div><p className="text-sm mt-1 max-w-3xl">Visão navegável e rastreável de como o processo funciona hoje.</p></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" onClick={() => navigate(`/processes/${id}`)}><ArrowLeft className="h-4 w-4 mr-1.5" />Voltar ao processo</Button><Button size="sm" className="gap-2"><ShieldCheck className="h-4 w-4" />Editar canvas</Button></div></div>
      <div className="flex flex-wrap gap-x-6 gap-y-2 mt-5 text-xs text-muted-foreground"><span><strong className="text-foreground">{canvas.activities.length}</strong> atividades</span><span><strong className="text-foreground">{canvas.systems.length}</strong> sistemas</span><span><strong className="text-foreground">{canvas.dataObjects.length}</strong> objetos de dados</span><span><strong className="text-foreground">{canvas.handoffs.length}</strong> handoffs</span><span>Atualizado {canvas.updatedAt}</span></div>
    </div>
    <div className="px-7 py-3 border-b border-border bg-card flex flex-wrap gap-3 items-center"><div className="flex items-center gap-1 rounded-lg bg-muted/60 p-1">{lensItems.map(item => <button key={item.id} onClick={() => setLens(item.id)} className={cn('flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs transition-colors', lens === item.id ? 'bg-card text-primary shadow-sm font-medium' : 'text-muted-foreground hover:text-foreground')}><item.icon className="h-3.5 w-3.5" />{item.label}</button>)}</div><div className="relative ml-auto min-w-[220px]"><Search className="absolute left-2.5 top-2 h-4 w-4 text-muted-foreground" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar no canvas" className="h-8 pl-8 text-xs" /></div><Select value={stageFilter} onValueChange={setStageFilter}><SelectTrigger className="h-8 w-[140px] text-xs"><SelectValue placeholder="Etapa" /></SelectTrigger><SelectContent><SelectItem value="all">Todas as etapas</SelectItem>{canvas.stages.map(s => <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Select value={systemFilter} onValueChange={setSystemFilter}><SelectTrigger className="h-8 w-[140px] text-xs"><SelectValue placeholder="Sistema" /></SelectTrigger><SelectContent><SelectItem value="all">Todos os sistemas</SelectItem>{canvas.systems.map(s => <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Select value={areaFilter} onValueChange={setAreaFilter}><SelectTrigger className="h-8 w-[130px] text-xs"><SelectValue placeholder="Área" /></SelectTrigger><SelectContent><SelectItem value="all">Todas as áreas</SelectItem>{canvas.areas.map(a => <SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select><Button variant="ghost" size="sm" className="h-8 text-xs" onClick={clearFilters}>Limpar</Button></div>
    <div className="px-7 py-4 flex items-center justify-between"><div className="flex items-center gap-2 text-xs text-muted-foreground"><CircleHelp className="h-4 w-4" />Selecione um elemento para explorar suas relações e evidências.</div><div className="flex items-center gap-1 border border-border rounded-md bg-card"><Button variant="ghost" size="icon" className="h-7 w-7" aria-label="Diminuir zoom" onClick={() => setZoom(z => Math.max(70, z - 10))}><Minus className="h-3.5 w-3.5" /></Button><span className="text-[11px] w-10 text-center">{zoom}%</span><Button variant="ghost" size="icon" className="h-7 w-7" aria-label="Aumentar zoom" onClick={() => setZoom(z => Math.min(130, z + 10))}><Plus className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7" aria-label="Ajustar à tela" onClick={() => setZoom(100)}><Maximize2 className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7" aria-label="Centralizar" onClick={() => setSelection(null)}><Focus className="h-3.5 w-3.5" /></Button></div></div>
    <div className="px-7 pb-8"><div className="rounded-xl border border-border bg-[#f6f7fb] dark:bg-muted/20 overflow-auto min-h-[560px] relative"><div className="min-w-[920px] p-6" style={{ transform: `scale(${zoom / 100})`, transformOrigin: 'top left', width: `${10000 / zoom}%` }}>{lens === 'handoffs' ? <HandoffsView canvas={canvas} onSelect={setSelection} selectedId={selection?.id} /> : <JourneyView canvas={canvas} activities={filteredActivities} lens={lens} onSelect={setSelection} selectedId={selection?.id} />}</div>{filteredActivities.length === 0 && lens !== 'handoffs' && <div className="absolute inset-0 flex items-center justify-center"><div className="bg-card border border-border rounded-lg px-6 py-5 text-center shadow-sm"><p className="font-medium text-sm text-foreground">Nenhum resultado encontrado</p><p className="text-xs mt-1">Ajuste a busca ou os filtros para continuar explorando.</p><Button variant="link" size="sm" onClick={clearFilters}>Limpar filtros</Button></div></div>}</div></div>
    {selection && selected && <ContextPanel canvas={canvas} selection={selection} selected={selected as any} onClose={() => setSelection(null)} onSelect={setSelection} />}
  </main></div>;
}

function JourneyView({ canvas, activities, lens, onSelect, selectedId }: { canvas: ProcessCanvas; activities: ProcessActivity[]; lens: Lens; onSelect: (s: Selection) => void; selectedId?: string }) { return <div className="flex gap-4 items-stretch">{canvas.stages.map(stage => { const stageActivities = activities.filter(a => a.stageId === stage.id); return <section key={stage.id} className="w-[212px] shrink-0"><div className="flex items-center gap-2 mb-3"><span className="flex items-center justify-center w-6 h-6 rounded-full bg-primary text-primary-foreground text-xs font-semibold">{stage.order}</span><h3 className="text-sm font-semibold">{stage.name}</h3></div><div className="space-y-3 min-h-[420px] rounded-xl border border-dashed border-border/80 p-2.5 bg-card/50">{stageActivities.map((activity, index) => <ActivityCard key={activity.id} activity={activity} canvas={canvas} lens={lens} index={index} selected={selectedId === activity.id} onClick={() => onSelect({ type: 'activity', id: activity.id })} onSelect={onSelect} />)}</div></section>; })}</div> }

function ActivityCard({ activity, canvas, lens, index, selected, onClick, onSelect }: { activity: ProcessActivity; canvas: ProcessCanvas; lens: Lens; index: number; selected: boolean; onClick: () => void; onSelect: (s: Selection) => void }) { const systems = activity.systemIds.map(id => canvas.systems.find(s => s.id === id)).filter(Boolean) as ProcessSystem[]; const data = canvas.dataInteractions.filter(x => x.activityId === activity.id); const actor = canvas.actors.find(x => x.id === activity.actorIds[0]); return <button onClick={onClick} className={cn('w-full text-left rounded-lg border bg-card p-3 shadow-sm transition-all hover:border-primary/50 hover:shadow-md', selected && 'border-primary ring-2 ring-primary/15', lens === 'systems' && systems.length > 0 && 'border-l-4 border-l-sky-500', lens === 'data' && data.length > 0 && 'border-l-4 border-l-amber-500', lens === 'actors' && 'border-l-4 border-l-violet-500')}><div className="flex gap-2"><span className="text-[10px] text-muted-foreground pt-0.5">0{index + 1}</span><span className="text-xs font-semibold leading-snug text-foreground">{activity.name}</span></div><div className="flex flex-wrap gap-1 mt-2">{actor && <span className="inline-flex items-center gap-1 text-[10px] rounded bg-violet-50 text-violet-700 dark:bg-violet-950/40 dark:text-violet-300 px-1.5 py-0.5"><UserRound className="h-2.5 w-2.5" />{actor.name}</span>}{systems.map(s => <span key={s.id} onClick={e => { e.stopPropagation(); onSelect({ type: 'system', id: s.id }); }} className="text-[10px] rounded bg-sky-50 text-sky-700 dark:bg-sky-950/40 dark:text-sky-300 px-1.5 py-0.5">{s.name}</span>)}{lens === 'data' && data.map(item => <span key={item.id} onClick={e => { e.stopPropagation(); onSelect({ type: 'data', id: item.dataObjectId }); }} className="text-[10px] rounded bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300 px-1.5 py-0.5">{canvas.dataObjects.find(d => d.id === item.dataObjectId)?.name} · {interactionLabel[item.interactionType]}</span>)}</div><div className="flex items-center justify-between mt-3 pt-2 border-t border-border/60"><span className="text-[10px] text-muted-foreground">{data.length} dado{data.length !== 1 ? 's' : ''} · {canvas.handoffs.filter(h => h.fromActivityId === activity.id || h.toActivityId === activity.id).length} handoff</span><span className="text-[10px] text-muted-foreground flex items-center gap-1"><Check className="h-3 w-3" />{evidenceLabel[activity.evidenceStatus]}</span></div></button> }

function HandoffsView({ canvas, onSelect, selectedId }: { canvas: ProcessCanvas; onSelect: (s: Selection) => void; selectedId?: string }) { return <div className="max-w-4xl mx-auto py-8"><div className="flex items-center gap-2 mb-6"><GitBranch className="h-5 w-5 text-primary" /><div><h2 className="text-base font-semibold">Transferências de trabalho e informação</h2><p className="text-xs">Conexões registradas entre atividades, pessoas e sistemas.</p></div></div><div className="space-y-3">{canvas.handoffs.map(h => { const from = canvas.activities.find(a => a.id === h.fromActivityId); const to = canvas.activities.find(a => a.id === h.toActivityId); return <button key={h.id} onClick={() => onSelect({ type: 'handoff', id: h.id })} className={cn('w-full rounded-lg border bg-card p-4 text-left flex items-center gap-4 hover:border-primary/50', selectedId === h.id && 'border-primary ring-2 ring-primary/15')}><div className="flex-1"><p className="text-xs font-semibold">{from?.name}</p><p className="text-[11px] text-muted-foreground mt-1">{h.fromActorId ? canvas.actors.find(a => a.id === h.fromActorId)?.name : 'Sistema'} · {h.fromSystemId ? canvas.systems.find(s => s.id === h.fromSystemId)?.name : 'Atividade'}</p></div><div className="flex flex-col items-center gap-1 text-primary"><span className="text-[10px] font-medium">{h.mechanism === 'unknown' ? 'A confirmar' : h.mechanism === 'manual' ? 'Manual' : h.mechanism}</span><ChevronRight className="h-5 w-5" /></div><div className="flex-1"><p className="text-xs font-semibold">{to?.name}</p><p className="text-[11px] text-muted-foreground mt-1">{h.toActorId ? canvas.actors.find(a => a.id === h.toActorId)?.name : 'Sistema'} · {h.dataObjectIds?.length || 0} dado(s)</p></div><Badge variant="outline" className="text-[10px] font-normal">{evidenceLabel[h.evidenceStatus]}</Badge></button>; })}</div></div> }

function ContextPanel({ canvas, selection, selected, onClose, onSelect }: { canvas: ProcessCanvas; selection: Exclude<Selection, null>; selected: ProcessActivity | ProcessSystem | ProcessDataObject | ProcessHandoff; onClose: () => void; onSelect: (s: Selection) => void }) { const isActivity = selection.type === 'activity'; const title = 'name' in selected ? selected.name : 'Handoff'; const activity = selected as ProcessActivity; const activityData = isActivity ? canvas.dataInteractions.filter(x => x.activityId === activity.id) : []; return <aside className="fixed right-0 top-14 bottom-0 w-[360px] max-w-[92vw] bg-card border-l border-border shadow-xl z-20 overflow-auto"><div className="p-5"><div className="flex justify-between items-start gap-3"><div><div className="text-[11px] uppercase tracking-wide text-muted-foreground mb-1">{selection.type === 'activity' ? 'Atividade' : selection.type === 'system' ? 'Sistema' : selection.type === 'data' ? 'Objeto de dado' : 'Handoff'}</div><h2 className="text-lg font-semibold leading-tight">{title}</h2></div><Button variant="ghost" size="icon" className="h-7 w-7" onClick={onClose} aria-label="Fechar painel"><X className="h-4 w-4" /></Button></div><Separator className="my-4" />{isActivity ? <><p className="text-sm leading-relaxed">{activity.description}</p><DetailSection title="Responsáveis">{activity.actorIds.map(id => { const a = canvas.actors.find(x => x.id === id); return <span key={id} className="chip" onClick={() => a?.areaId && onSelect({ type: 'activity', id: activity.id })}>{a?.name} · {a?.role}</span>; })}</DetailSection><DetailSection title="Sistemas utilizados">{activity.systemIds.map(id => { const s = canvas.systems.find(x => x.id === id); return <button key={id} onClick={() => onSelect({ type: 'system', id })} className="text-xs text-primary hover:underline block">{s?.name}{s?.moduleOrScreen ? ` · ${s.moduleOrScreen}` : ''}</button>; })}</DetailSection><DetailSection title="Dados tratados">{activityData.map(item => { const d = canvas.dataObjects.find(x => x.id === item.dataObjectId); return <button key={item.id} onClick={() => onSelect({ type: 'data', id: item.dataObjectId })} className="w-full flex justify-between text-xs py-1 text-left hover:text-primary"><span>{d?.name}</span><span className="text-muted-foreground">{interactionLabel[item.interactionType]}</span></button>; })}</DetailSection></> : <GenericDetails canvas={canvas} selection={selection} selected={selected} onSelect={onSelect} />}<div className="mt-6 flex items-center gap-2 text-xs text-muted-foreground"><Check className="h-4 w-4 text-green-600" />Evidência: <Badge variant="outline" className="font-normal">{evidenceLabel[(selected as any).evidenceStatus || 'declared']}</Badge></div></div></aside> }

function DetailSection({ title, children }: { title: string; children: ReactNode }) { return <section className="mt-5"><h3 className="text-xs font-semibold text-foreground mb-2">{title}</h3><div className="space-y-1.5">{children}</div></section> }
function GenericDetails({ canvas, selection, selected, onSelect }: { canvas: ProcessCanvas; selection: Exclude<Selection, null>; selected: any; onSelect: (s: Selection) => void }) { if (selection.type === 'system') { const uses = canvas.activities.filter(a => a.systemIds.includes(selected.id)); return <><p className="text-sm">{selected.description || 'Descrição ainda não registrada.'}</p><p className="text-xs text-muted-foreground mt-2">Módulo/tela: {selected.moduleOrScreen || 'A confirmar'}</p><DetailSection title="Atividades"><div className="space-y-1">{uses.map((a: ProcessActivity) => <button key={a.id} onClick={() => onSelect({ type: 'activity', id: a.id })} className="text-xs text-primary hover:underline block">{a.name}</button>)}</div></DetailSection></>; } if (selection.type === 'data') { const interactions = canvas.dataInteractions.filter(i => i.dataObjectId === selected.id); return <><p className="text-sm">{selected.description || 'Descrição ainda não registrada.'}</p><p className="text-xs text-muted-foreground mt-2">Categoria: {selected.category || 'A confirmar'}{selected.containsSensitiveData ? ' · Contém dado sensível' : ''}</p><DetailSection title="Jornada funcional do dado">{interactions.map((i: any) => <button key={i.id} onClick={() => onSelect({ type: 'activity', id: i.activityId })} className="w-full flex justify-between text-xs py-1 text-left hover:text-primary"><span>{canvas.activities.find(a => a.id === i.activityId)?.name}</span><span className="text-muted-foreground">{interactionLabel[i.interactionType]}</span></button>)}</DetailSection></>; } const from = canvas.activities.find(a => a.id === selected.fromActivityId); const to = canvas.activities.find(a => a.id === selected.toActivityId); return <><p className="text-sm">{from?.name} <span className="text-muted-foreground">→</span> {to?.name}</p><DetailSection title="Mecanismo"><span className="text-xs">{selected.mechanism === 'unknown' ? 'A confirmar' : selected.mechanism === 'manual' ? 'Manual' : selected.mechanism}</span></DetailSection><DetailSection title="Dados movimentados">{(selected.dataObjectIds || []).map((id: string) => <button key={id} onClick={() => onSelect({ type: 'data', id })} className="text-xs text-primary hover:underline block">{canvas.dataObjects.find(d => d.id === id)?.name}</button>)}</DetailSection>{selected.notes && <p className="text-xs text-muted-foreground mt-4">{selected.notes}</p>}</>; }
