import { useState, useRef, useCallback, useEffect } from "react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Plus, Trash2, GripVertical } from "lucide-react";
import { ViewEditToggle } from "./ViewEditToggle";
import { cn } from "@/lib/utils";

export interface FieldRow {
  id: string;
  name: string;
  format: string;
  helpText: string;
  visibleAtStages: string;
  editableAtStages: string;
  requiredAtStages: string;
  input: string;
  notes: string;
}

const initialFields: FieldRow[] = [
  { id: "1", name: "Material Code", format: "Text", helpText: "Search and select from the SAP material catalog", visibleAtStages: "All", editableAtStages: "Request Creation", requiredAtStages: "Request Creation", input: "List of all active material codes from SAP", notes: "" },
  { id: "2", name: "Material Description", format: "Text", helpText: "Auto-filled from SAP after material code is selected", visibleAtStages: "All", editableAtStages: "", requiredAtStages: "", input: "Auto-populated from SAP master data lookup", notes: "Read-only" },
  { id: "3", name: "Quantity", format: "Number", helpText: "Enter the quantity of units being requested", visibleAtStages: "All", editableAtStages: "Request Creation", requiredAtStages: "Request Creation", input: "Manual input", notes: "" },
  { id: "4", name: "Unit Price", format: "Decimal", helpText: "Unit price fetched from SAP. May be overridden at approval.", visibleAtStages: "All", editableAtStages: "Approval", requiredAtStages: "", input: "Auto-populated from SAP master data lookup. Editable by manager at approval.", notes: "" },
  { id: "5", name: "Total Value", format: "Decimal", helpText: "Calculated automatically as Quantity × Unit Price", visibleAtStages: "All", editableAtStages: "", requiredAtStages: "", input: "Auto-calculated (Quantity × Unit Price)", notes: "Read-only. Determines approval routing (≤ $5K threshold)" },
  { id: "6", name: "Cost Center", format: "Dropdown", helpText: "Select the cost center that will be charged for this purchase", visibleAtStages: "All", editableAtStages: "Request Creation, Approval", requiredAtStages: "Request Creation", input: "Options from Workday (filtered by requester's department)", notes: "" },
  { id: "7", name: "Plant Location", format: "Dropdown", helpText: "Select the plant or location where the material will be delivered", visibleAtStages: "All", editableAtStages: "Request Creation", requiredAtStages: "Request Creation", input: "List of active plant codes from SAP", notes: "" },
  { id: "8", name: "Justification", format: "Text area", helpText: "Briefly describe the business reason for this purchase request", visibleAtStages: "Approval, PO Creation", editableAtStages: "Request Creation, Approval", requiredAtStages: "Approval", input: "Manual input", notes: "Required by manager only for requests above $5K" },
  { id: "9", name: "Requested Delivery Date", format: "Date", helpText: "Date by which the material is needed. Must be at least 5 business days from today.", visibleAtStages: "All", editableAtStages: "Request Creation", requiredAtStages: "Request Creation", input: "Manual input (date picker)", notes: "" },
  { id: "10", name: "Purchase Order Number", format: "Text", helpText: "Auto-generated by SAP after purchase order is created", visibleAtStages: "PO Creation", editableAtStages: "", requiredAtStages: "", input: "Auto-generated by SAP at PO Creation stage", notes: "Read-only. Shown to requester in the final notification email." },
  { id: "11", name: "Supplier Name", format: "Text", helpText: "Name of the supplier for this purchase", visibleAtStages: "All", editableAtStages: "", requiredAtStages: "", input: "Auto-populated from SAP", notes: "" },
];

const formatVariant = (format: string) => {
  switch (format) {
    case "Text": return "secondary" as const;
    case "Text area": return "secondary" as const;
    case "Number": return "outline" as const;
    case "Decimal": return "outline" as const;
    case "Dropdown": return "default" as const;
    case "Date": return "secondary" as const;
    case "Boolean": return "outline" as const;
    default: return "secondary" as const;
  }
};

let nextId = 12;

interface ToBeFieldsProps {
  externalFields?: FieldRow[];
}

export function ToBeFields({ externalFields }: ToBeFieldsProps) {
  const [fields, setFields] = useState<FieldRow[]>(initialFields);
  const [isEditMode, setIsEditMode] = useState(false);
  const [draggedId, setDraggedId] = useState<string | null>(null);
  const [dropTargetId, setDropTargetId] = useState<string | null>(null);
  const [highlightedIds, setHighlightedIds] = useState<Set<string>>(new Set());
  const dragCounter = useRef<Record<string, number>>({});
  const prevExtLen = useRef(0);
  const tableEndRef = useRef<HTMLDivElement>(null);

  // Watch for new external fields
  useEffect(() => {
    if (!externalFields || externalFields.length <= prevExtLen.current) {
      prevExtLen.current = externalFields?.length ?? 0;
      return;
    }
    const newFields = externalFields.slice(prevExtLen.current);
    prevExtLen.current = externalFields.length;

    setFields(prev => [...prev, ...newFields]);

    const newIds = new Set(newFields.map(f => f.id));
    setHighlightedIds(prev => new Set([...prev, ...newIds]));

    // Scroll to bottom after render
    setTimeout(() => {
      tableEndRef.current?.scrollIntoView({ behavior: "smooth", block: "end" });
    }, 100);

    // Remove highlight after 2s
    setTimeout(() => {
      setHighlightedIds(prev => {
        const next = new Set(prev);
        newIds.forEach(id => next.delete(id));
        return next;
      });
    }, 2000);
  }, [externalFields]);

  const updateField = (id: string, key: keyof FieldRow, value: string) => {
    setFields(prev => prev.map(f => f.id === id ? { ...f, [key]: value } : f));
  };

  const addField = () => {
    setFields(prev => [...prev, { id: String(nextId++), name: "", format: "Text", helpText: "", visibleAtStages: "", editableAtStages: "", requiredAtStages: "", input: "", notes: "" }]);
  };

  const removeField = (id: string) => {
    setFields(prev => prev.filter(f => f.id !== id));
  };

  const handleDragStart = useCallback((e: React.DragEvent, id: string) => {
    setDraggedId(id);
    e.dataTransfer.effectAllowed = "move";
    const el = e.currentTarget as HTMLElement;
    e.dataTransfer.setDragImage(el, 0, el.offsetHeight / 2);
  }, []);

  const handleDragEnter = useCallback((e: React.DragEvent, overId: string) => {
    e.preventDefault();
    dragCounter.current[overId] = (dragCounter.current[overId] || 0) + 1;
    if (draggedId && draggedId !== overId) {
      setDropTargetId(overId);
    }
  }, [draggedId]);

  const handleDragLeave = useCallback((e: React.DragEvent, overId: string) => {
    e.preventDefault();
    dragCounter.current[overId] = (dragCounter.current[overId] || 0) - 1;
    if (dragCounter.current[overId] <= 0) {
      dragCounter.current[overId] = 0;
      if (dropTargetId === overId) setDropTargetId(null);
    }
  }, [dropTargetId]);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = "move";
  }, []);

  const handleDrop = useCallback((e: React.DragEvent, overId: string) => {
    e.preventDefault();
    if (!draggedId || draggedId === overId) return;
    setFields(prev => {
      const fromIdx = prev.findIndex(f => f.id === draggedId);
      const toIdx = prev.findIndex(f => f.id === overId);
      if (fromIdx === -1 || toIdx === -1) return prev;
      const next = [...prev];
      const [moved] = next.splice(fromIdx, 1);
      next.splice(toIdx, 0, moved);
      return next;
    });
    setDropTargetId(null);
    dragCounter.current = {};
  }, [draggedId]);

  const handleDragEnd = useCallback(() => {
    setDraggedId(null);
    setDropTargetId(null);
    dragCounter.current = {};
  }, []);

  const renderCell = (field: FieldRow, key: keyof FieldRow, placeholder: string) => {
    if (isEditMode) {
      return <Input value={field[key]} onChange={e => updateField(field.id, key, e.target.value)} placeholder={placeholder} className="text-sm h-8" />;
    }
    return <span className="text-sm text-muted-foreground">{field[key] || "—"}</span>;
  };

  return (
    <div className="flex-1 flex flex-col h-full overflow-hidden">
      <div className="sticky top-0 z-10 bg-card border-b border-border px-8 py-3 flex items-center justify-between">
        <ViewEditToggle isEditMode={isEditMode} onToggle={setIsEditMode} />
        {isEditMode && (
          <Button size="sm" variant="outline" className="gap-2" onClick={addField}>
            <Plus className="h-3.5 w-3.5" />
            Add Field
          </Button>
        )}
      </div>

      <div className="p-6 overflow-auto">
        <h2 className="text-lg font-semibold text-foreground mb-1">Fields</h2>
        <p className="text-sm text-muted-foreground mb-6">Fields identified in the TO-BE process requirements.</p>

        <div className="border border-border rounded-lg overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow className="bg-muted/40">
                <TableHead className="w-[36px]" />
                <TableHead className="text-xs font-semibold">Field Name</TableHead>
                <TableHead className="text-xs font-semibold w-[120px]">Format</TableHead>
                <TableHead className="text-xs font-semibold">Help Text</TableHead>
                <TableHead className="text-xs font-semibold">Visible at stages</TableHead>
                <TableHead className="text-xs font-semibold">Editable at stages</TableHead>
                <TableHead className="text-xs font-semibold">Required at stages</TableHead>
                <TableHead className="text-xs font-semibold">Input</TableHead>
                <TableHead className="text-xs font-semibold">Notes</TableHead>
                {isEditMode && <TableHead className="text-xs font-semibold w-[50px]" />}
              </TableRow>
            </TableHeader>
            <TableBody>
              {fields.map((field) => (
                <TableRow
                  key={field.id}
                  draggable={isEditMode}
                  onDragStart={e => handleDragStart(e, field.id)}
                  onDragEnter={e => handleDragEnter(e, field.id)}
                  onDragLeave={e => handleDragLeave(e, field.id)}
                  onDragOver={handleDragOver}
                  onDrop={e => handleDrop(e, field.id)}
                  onDragEnd={handleDragEnd}
                  className={cn(
                    "transition-all duration-200",
                    draggedId === field.id && "opacity-40 scale-[0.98]",
                    dropTargetId === field.id && draggedId !== field.id && "border-t-2 border-t-primary bg-primary/[0.04] shadow-[inset_0_2px_0_0_hsl(var(--primary))]"
                  )}
                  style={
                    highlightedIds.has(field.id)
                      ? {
                          animation: "fieldHighlight 2s ease-out forwards",
                        }
                      : undefined
                  }
                >
                  <TableCell className="px-1">
                    <GripVertical className={cn(
                      "h-4 w-4 transition-colors",
                      isEditMode ? "text-muted-foreground cursor-grab active:cursor-grabbing" : "text-muted-foreground/30"
                    )} />
                  </TableCell>
                  <TableCell>
                    {isEditMode ? (
                      <Input value={field.name} onChange={e => updateField(field.id, "name", e.target.value)} placeholder="Field name..." className="text-sm h-8" />
                    ) : (
                      <span className="text-sm font-medium">{field.name}</span>
                    )}
                  </TableCell>
                  <TableCell>
                    {isEditMode ? (
                      <Select value={field.format} onValueChange={v => updateField(field.id, "format", v)}>
                        <SelectTrigger className="h-8 text-xs">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="Text">Text</SelectItem>
                          <SelectItem value="Text area">Text area</SelectItem>
                          <SelectItem value="Number">Number</SelectItem>
                          <SelectItem value="Decimal">Decimal</SelectItem>
                          <SelectItem value="Dropdown">Dropdown</SelectItem>
                          <SelectItem value="Date">Date</SelectItem>
                          <SelectItem value="Boolean">Boolean</SelectItem>
                        </SelectContent>
                      </Select>
                    ) : (
                      <Badge variant={formatVariant(field.format)} className="text-xs">{field.format}</Badge>
                    )}
                  </TableCell>
                  <TableCell>{renderCell(field, "helpText", "Help text...")}</TableCell>
                  <TableCell>{renderCell(field, "visibleAtStages", "e.g. All, Request Creation")}</TableCell>
                  <TableCell>{renderCell(field, "editableAtStages", "e.g. Request Creation, Approval")}</TableCell>
                  <TableCell>{renderCell(field, "requiredAtStages", "e.g. Request Creation")}</TableCell>
                  <TableCell>{renderCell(field, "input", "e.g. Manual input")}</TableCell>
                  <TableCell>{renderCell(field, "notes", "Notes...")}</TableCell>
                  {isEditMode && (
                    <TableCell>
                      <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-destructive" onClick={() => removeField(field.id)}>
                        <Trash2 className="h-3.5 w-3.5" />
                      </Button>
                    </TableCell>
                  )}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
        <div ref={tableEndRef} />
      </div>
    </div>
  );
}
